# Generated by Django 5.1.2 on 2024-11-06 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_cards_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker_number',
            name='worker_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
