# Generated by Django 5.1.2 on 2024-11-07 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_worker_number_worker_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='code',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
