# Generated by Django 5.1.2 on 2024-11-07 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_cards_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cards',
            name='code',
        ),
        migrations.AddField(
            model_name='workertype',
            name='code',
            field=models.CharField(default='XX', max_length=5),
        ),
    ]
